In [66]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/abhishek14398/salary-dataset-simple-linear-regression/Salary_dataset.csv

In [67]:
df = pd.read_csv("/kaggle/input/datasets/abhishek14398/salary-dataset-simple-linear-regression/Salary_dataset.csv")
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [68]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [69]:
X , y = df['YearsExperience'],df['Salary']
print(X[:2])
print(y[:2])

0    1.2
1    1.4
Name: YearsExperience, dtype: float64
0    39344.0
1    46206.0
Name: Salary, dtype: float64

In [70]:
X_data = np.array(X).reshape(-1,1)
y_data = np.array(y).reshape(-1,1)
print(X_data[:2])
print(y_data[:2])

[[1.2]
 [1.4]]
[[39344.]
 [46206.]]

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train_data, X_test_data, y_train_data,y_test_data = train_test_split(X_data,y_data,test_size=0.2,random_state=42)

X_scale = StandardScaler()
y_scale = StandardScaler() 

X_train_scaled = X_scale.fit_transform(X_train_data)
y_train_scaled = y_scale.fit_transform(y_train_data)

X_test_scaled = X_scale.transform(X_test_data)
y_test_scaled = y_scale.transform(y_test_data)

print(X_train_scaled[:2])
print(X_test_scaled[:2])

[[1.77445774]
 [1.21912622]]
[[ 1.5315002 ]
 [-0.09978613]]

In [72]:
import torch

X_train_scaled_torch = torch.tensor(X_train_scaled, dtype = torch.float32)
X_test_scaled_torch = torch.tensor(X_test_scaled, dtype = torch.float32)
y_train_scaled_torch = torch.tensor(y_train_scaled, dtype = torch.float32)
y_test_scaled_torch = torch.tensor(y_test_scaled, dtype = torch.float32)

print(X_train_scaled_torch[:2])
print(X_test_scaled_torch[:2])

tensor([[1.7745],
        [1.2191]])
tensor([[ 1.5315],
        [-0.0998]])

In [73]:
import torch.nn as nn
import torch.optim as optim 

model = nn.Linear(1,1)
loss_fun = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

epochs = 500
for epoch in range(epochs):
    model.train()
    y_trained_output = model(X_train_scaled_torch)
    loss = loss_fun(y_trained_output,y_train_scaled_torch)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoch % 100 == 0:
        print(loss.item())



from sklearn.metrics import r2_score,mean_absolute_error
model.eval()
with torch.no_grad():
    y_test_output = model(X_test_scaled_torch)
    r2 = r2_score(y_test_scaled_torch,y_test_output)
    mae = mean_absolute_error(y_test_scaled_torch,y_test_output)
    print(f"r2_score: {r2}")
    print(f"mae: {mae}")

0.2310546636581421
0.03889993205666542
0.03552034869790077
0.035460907965898514
0.035459861159324646
r2_score: 0.9024413050545808
mae: 0.22738895316918692

In [74]:
X = [[1.7]]
model.eval()
with torch.no_grad():
    x_scaled_output = X_scale.transform(X)
    x_tensor = torch.tensor(x_scaled_output,dtype = torch.float32)
    y_output = model(x_tensor)
    real_data = y_scale.inverse_transform(y_output)
    print(real_data)

[[40400.784079]]